server:
  port: 9000
spring: 
  application:
  name: eureka-server-2
profiles: 
active:   server2
eureka:
  instance:
    hostname: server2
    lease-renewal-interval-in-seconds: 3  # 心跳间隔
    lease-expiration-duration-in-seconds: 7 # 服务失效时间： 如果多久没有收到请求，则可以删除服务
  client:
    eureka-service-url-poll-interval-seconds: 60 #客户端从Eureka Server集群里更新Eureka Server信息的频率
    registry-fetch-interval-seconds: 5 # 定义从注册中心获取注册服务的信息
    serviceUrl:
      defaultZone: http://server1:8000/eureka/
  server: 
    enable-self-preservation: false # Eureka Server 自我保护系数，当enable-self-preservation=true时，启作用
    eviction-interval-timer-in-ms: 3000  # 设置清理间隔,单位为毫秒,默认为0
    wait-time-in-ms-when-sync-empty: 60000 # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    peer-eureka-nodes-update-interval-ms: 60000 # 集群之间相互更新节点信息的时间频率

