server:
  port: 6001
spring:
  application:
    name: loran-order
eureka:
  client:
    service-url:
      defaultZone:  http://server1:8000/eureka/
  instance: 
    instance-id: order-6001
    prefer-ip-address: true 